/**
 * Firebase Auth wiring.
 *
 * Config comes from environment variables (see .env.example). No credentials
 * are committed — put real values in .env.local for development and in the
 * Vercel project's environment variables for production.
 *
 * Firebase Auth (Spark/free tier: 50k monthly active users) handles:
 *  - Google OAuth sign-in (user creates the Firebase project; the OAuth
 *    client ID is generated by Firebase automatically)
 *  - Email + password sign-up/login (passwords are hashed by Firebase
 *    server-side with scrypt; they never touch this code or repo)
 *  - Sign-out
 *
 * If config is missing, `auth` is null and `isAuthConfigured()` returns
 * false — the UI shows a graceful "sign-in is being connected" state instead
 * of crashing. Sign-in fully works once the setup checklist in
 * launch/auth-paddle-checklist.md is done.
 */

import { initializeApp, type FirebaseApp } from "firebase/app";
import { getAuth, type Auth } from "firebase/auth";

const config = {
  apiKey: import.meta.env.VITE_FIREBASE_API_KEY as string | undefined,
  authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN as string | undefined,
  projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID as string | undefined,
  appId: import.meta.env.VITE_FIREBASE_APP_ID as string | undefined,
};

function hasConfig(): boolean {
  return Boolean(config.apiKey && config.authDomain && config.projectId && config.appId);
}

let app: FirebaseApp | null = null;
let auth: Auth | null = null;

if (hasConfig()) {
  app = initializeApp(config);
  auth = getAuth(app);
}

export function isAuthConfigured(): boolean {
  return auth !== null;
}

export { auth };
